// BURGER BUILDER
export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT';
export const SET_INGREDIENTS = 'SET_INGREDIENTS';
export const RESET_INGREDIENTS = 'RESET_INGREDIENTS';
export const FETCH_INGREDIENT_FAILED = 'FETCH_INGREDIENT_FAILED';
// ORDER PLACING
export const PURCHASE_SUCCESS = 'PURCHASE_SUCCESS';
export const PURCHASE_FAIL = 'PURCHASE_FAIL';
export const PURCHASE_LOADING = 'PURCHASE_LOADING';

// GET ORDER DETAILS

export const GET_ORDERS_SUCCESS = 'GET_ORDERS_SUCCESS';
export const GET_ORDERS_FAIL = 'GET_ORDERS_FAIL';
export const GET_ORDERS_LOADING = 'GET_ORDERS_LOADING';

// AUTHENICATION

export const AUTHENICATION_SUCCESSS = 'AUTHENICATION_SUCCESSS';
export const AUTHENICATION_FAIL = 'AUTHENICATION_FAIL';
export const AUTHENICATION_LOADING = 'AUTHENICATION_LOADING';
export const AUTHENICATION_LOGOUT = 'AUTHENICATION_LOGOUT';

export const CHECK_AUTENTICATION_FROM_LOCAL = 'CHECK_AUTENTICATION_FROM_LOCAL';
